/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Xan
 */

import java.math.BigDecimal;

public class InterestGUI extends javax.swing.JFrame {

    /**
     * Creates new form InterestGUI
     */
    public InterestGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSimpleClear = new javax.swing.JButton();
        lblSimpleInterest = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblSimpleTotal = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSimplePrincipal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSimpleRate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSimpleTime = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCompoundPrincipal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCompoundRate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCompoundTime = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCompoundAmount = new javax.swing.JTextField();
        btnCompoundClear = new javax.swing.JButton();
        btnCompoundCalculate = new javax.swing.JButton();
        cmbPeriod = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Riten0.3 Interest Calculator");
        setBackground(new java.awt.Color(195, 230, 226));
        setFont(new java.awt.Font("Cascadia Mono", 0, 10)); // NOI18N
        setLocation(new java.awt.Point(40, 40));
        setMaximumSize(new java.awt.Dimension(720, 480));
        setMinimumSize(new java.awt.Dimension(720, 480));
        setName("mainFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(720, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(720, 480));

        jTabbedPane1.setFont(jTabbedPane1.getFont());

        jLabel2.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        jLabel2.setText("SIMPLE INTEREST");

        btnSimpleClear.setFont(new java.awt.Font("Cascadia Mono", 1, 12)); // NOI18N
        btnSimpleClear.setText("Clear");
        btnSimpleClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpleClearActionPerformed(evt);
            }
        });

        lblSimpleInterest.setBackground(new java.awt.Color(255, 255, 255));
        lblSimpleInterest.setFont(new java.awt.Font("Cascadia Mono", 1, 24)); // NOI18N
        lblSimpleInterest.setForeground(new java.awt.Color(12, 22, 21));
        lblSimpleInterest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSimpleInterest.setText("0.0000000");
        lblSimpleInterest.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(12, 22, 21), 5, true));

        jLabel12.setFont(new java.awt.Font("Cascadia Mono", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(12, 22, 21));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Interest Amount");

        lblSimpleTotal.setBackground(new java.awt.Color(255, 255, 255));
        lblSimpleTotal.setFont(new java.awt.Font("Cascadia Mono", 1, 24)); // NOI18N
        lblSimpleTotal.setForeground(new java.awt.Color(12, 22, 21));
        lblSimpleTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSimpleTotal.setText("0.0000000");
        lblSimpleTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(12, 22, 21), 5, true));

        jLabel13.setFont(new java.awt.Font("Cascadia Mono", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(12, 22, 21));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Total (Principal + Interest)");

        jLabel1.setFont(new java.awt.Font("Cascadia Mono", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setLabelFor(txtSimplePrincipal);
        jLabel1.setText("Principal");

        txtSimplePrincipal.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        txtSimplePrincipal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSimplePrincipal.setText("0");
        txtSimplePrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSimplePrincipal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSimplePrincipalFocusLost(evt);
            }
        });
        txtSimplePrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSimplePrincipalActionPerformed(evt);
            }
        });
        txtSimplePrincipal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSimplePrincipalKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cascadia Mono", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setLabelFor(txtSimpleRate);
        jLabel3.setText("Rate (%)");

        txtSimpleRate.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        txtSimpleRate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSimpleRate.setText("0.0");
        txtSimpleRate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSimpleRate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSimpleRateFocusLost(evt);
            }
        });
        txtSimpleRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSimpleRateActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cascadia Mono", 1, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setLabelFor(txtSimpleTime);
        jLabel4.setText("Years");

        txtSimpleTime.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        txtSimpleTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSimpleTime.setText("1");
        txtSimpleTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSimpleTime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSimpleTimeFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSimpleClear, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSimpleInterest, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSimpleTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtSimplePrincipal))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSimpleRate, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSimpleTime, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(81, 81, 81))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnSimpleClear))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(lblSimpleInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(lblSimpleTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSimpleTime))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSimpleRate))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSimplePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Simple Interest", jPanel1);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("COMPOUND INTEREST");

        jLabel7.setText("Principal");

        txtCompoundPrincipal.setText("0.0");

        jLabel8.setText("Rate (%)");

        txtCompoundRate.setText("0.0");

        jLabel9.setText("Time (Years)");

        txtCompoundTime.setText("1");

        jLabel10.setText("Compounds:");

        jLabel11.setText("Amount");

        txtCompoundAmount.setText("0.00");

        btnCompoundClear.setText("Clear");
        btnCompoundClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompoundClearActionPerformed(evt);
            }
        });

        btnCompoundCalculate.setText("Calculate");
        btnCompoundCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompoundCalculateActionPerformed(evt);
            }
        });

        cmbPeriod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Daily (365)", "Daily (366)", "Weekly", "Biweekly", "Semimonthly", "Monthly", "Bimonthly", "Quarterly", "Semiannually", "Annually" }));
        cmbPeriod.setSelectedIndex(9);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(btnCompoundClear, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCompoundCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCompoundRate, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCompoundPrincipal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCompoundTime))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCompoundAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCompoundAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCompoundPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(txtCompoundTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCompoundRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(cmbPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCompoundClear)
                    .addComponent(btnCompoundCalculate))
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Compound Interest", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSimpleRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSimpleRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSimpleRateActionPerformed

    private void btnSimpleClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpleClearActionPerformed
        
       txtSimplePrincipal.setText("0");
       
       txtSimpleRate.setText("0.0");
       
       txtSimpleTime.setText("1");
       
       lblSimpleInterest.setText("0.00");
       
       lblSimpleTotal.setText("0.00");
        
    }//GEN-LAST:event_btnSimpleClearActionPerformed

    private void performSimpleInterestFeature(){
    
        SimpleInterestCalculator calc = new SimpleInterestCalculator();
        
        BigDecimal principal = new BigDecimal(txtSimplePrincipal.getText());
        
        BigDecimal rate = new BigDecimal(txtSimpleRate.getText());
        
        BigDecimal time = new BigDecimal(txtSimpleTime.getText());
        
        BigDecimal interest = new BigDecimal("0.0");
        
        interest = calc.calculateInterest(principal, rate, time);
        
        BigDecimal total = principal.add(interest);
        
        lblSimpleInterest.setText(String.valueOf(interest));
        
        lblSimpleTotal.setText(String.valueOf(total));
        
    }
    
    private void btnCompoundClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompoundClearActionPerformed
        
        txtCompoundPrincipal.setText("0.00");
        
        txtCompoundRate.setText("0.00");
        
        txtCompoundTime.setText("1");
        
        cmbPeriod.setSelectedItem("Annually");
        
        txtCompoundAmount.setText("0.00");
        
    }//GEN-LAST:event_btnCompoundClearActionPerformed

    private void btnCompoundCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompoundCalculateActionPerformed
        
        CompoundInterestCalculator calc = new CompoundInterestCalculator();
        
        BigDecimal principal = new BigDecimal(txtCompoundPrincipal.getText());
        
        BigDecimal rate = new BigDecimal(txtCompoundRate.getText());
        
        BigDecimal time = new BigDecimal(txtCompoundTime.getText());
        
        String compounder = cmbPeriod.getSelectedItem().toString();
        
        /*PeriodConverter conv = new PeriodConverter();
        
        BigDecimal period = conv.convert(compounder);*/
        
        BigDecimal period = new PeriodConverter().convert(compounder);
     
        BigDecimal interest = calc.calculateInterest(principal, rate, time, period);
        
        txtCompoundAmount.setText(String.valueOf(interest));
        
    }//GEN-LAST:event_btnCompoundCalculateActionPerformed

    private void txtSimplePrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSimplePrincipalActionPerformed
        
       
        
    }//GEN-LAST:event_txtSimplePrincipalActionPerformed

    private void txtSimplePrincipalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSimplePrincipalKeyTyped
       
       
       
    }//GEN-LAST:event_txtSimplePrincipalKeyTyped

    private void txtSimplePrincipalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSimplePrincipalFocusLost
        
        this.performSimpleInterestFeature();
        
    }//GEN-LAST:event_txtSimplePrincipalFocusLost

    private void txtSimpleRateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSimpleRateFocusLost
        
        this.performSimpleInterestFeature();
        
    }//GEN-LAST:event_txtSimpleRateFocusLost

    private void txtSimpleTimeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSimpleTimeFocusLost
        
        this.performSimpleInterestFeature();
        
    }//GEN-LAST:event_txtSimpleTimeFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterestGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompoundCalculate;
    private javax.swing.JButton btnCompoundClear;
    private javax.swing.JButton btnSimpleClear;
    private javax.swing.JComboBox<String> cmbPeriod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblSimpleInterest;
    private javax.swing.JLabel lblSimpleTotal;
    private javax.swing.JTextField txtCompoundAmount;
    private javax.swing.JTextField txtCompoundPrincipal;
    private javax.swing.JTextField txtCompoundRate;
    private javax.swing.JTextField txtCompoundTime;
    private javax.swing.JTextField txtSimplePrincipal;
    private javax.swing.JTextField txtSimpleRate;
    private javax.swing.JTextField txtSimpleTime;
    // End of variables declaration//GEN-END:variables
}
